# Generated by Django 5.0.7 on 2024-09-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0004_alter_articlecontent_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecontent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
