# Generated by Django 5.0.7 on 2024-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0012_alter_article_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
