# Generated by Django 5.0.7 on 2024-10-22 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0013_article_tags"),
        ("article", "0017_article_tags"),
    ]

    operations = []
