# Generated by Django 5.0.7 on 2024-10-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0018_merge_0013_article_tags_0017_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="createdBy",
            field=models.IntegerField(null=True),
        ),
    ]
