# Generated by Django 5.0.7 on 2024-12-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_favoritecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='¿Destacar este artículo?'),
        ),
    ]
