# Generated by Django 5.0.7 on 2024-08-30 01:37

from django.db import migrations


def add_default_roles(apps, schema_editor):
    Role = apps.get_model("roles", "Role")

    Role.objects.create(
        name="Administrador", description="Rol de administrador con acceso completo"
    )

    Role.objects.create(
        name="Editor", description="Rol de editor con privilegios de edición"
    )

    Role.objects.create(name="Autor", description="Rol de autor con privilegios de escritura")

    Role.objects.create(
        name="Publicador", description="Rol de publicador con privilegios de publicación"
    )

    Role.objects.create(
        name="Visitante", description="Rol de visitante con acceso de lectura a atriculos del tipo free"
    )

    Role.objects.create(
        name="Suscriptor", description="Rol de suscriptor con privilegios para suscribirse a categorías, leer, comentar y evaluar artículos a los cuales tiene acceso"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_default_roles),
    ]
