# Generated by Django 5.0.7 on 2024-08-30 01:37

from django.db import migrations

def add_default_roles(apps, schema_editor):
    Role = apps.get_model('roles', 'Role')
    
    Role.objects.create(
        name='Administrador',
        description='Administrator role with full access'
    )
    
    Role.objects.create(
        name='Editor',
        description='Editor role with editing privileges'
    )
    
    Role.objects.create(
        name='Autor',
        description='Author role with writing privileges'
    )

    Role.objects.create(    
        name='Publicador',
        description='Publisher role with publishing privileges'
    )

    Role.objects.create(
        name='Visitante',
        description='Visitor role with read-only access'
    )

    Role.objects.create(
        name='Suscriptor',
        description='Subscriber role with subscription privileges'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_roles),
    ]
