# Generated by Django 5.0.7 on 2024-08-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0002_add_default_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(related_name="roles", to="roles.permission"),
        ),
    ]
