# Generated by Django 5.0.7 on 2024-08-30 02:04

from django.db import migrations


def add_default_roles(apps, schema_editor):
    Permission = apps.get_model("roles", "permission")
    Role = apps.get_model("roles", "Role")

    Permission.objects.create(
        name="ver_inicio",
        description="Ver solamente pantalla de inicio y categorías free",
    )

    Permission.objects.create(
        name="ver_categorias_suscriptor",
        description="Ver las categorías del suscriptor",
    )

    Permission.objects.create(
        name="ver_categorias_pago",
        description="Ver las categorías del suscriptor",
    )

    Permission.objects.create(
        name="crear_articulos",
        description="Crear articulos en aquellas categorías que pueda crear",
    )

    Permission.objects.create(
        name="editar_articulos",
        description="Editar articulos en aquellas categorías que pueda editar",
    )

    Permission.objects.create(
        name="moderar_articulos",
        description="Moderar articulos en aquellas categorías que pueda moderar",
    )

    Permission.objects.create(
        name="publicar_comentarios", description="Publicar comentarios en articulos"
    )

    Permission.objects.create(
        name="leer_comentarios", description="Leer comentarios en articulos"
    )

    Permission.objects.create(
        name="evaluar_articulos", description="Moderar comentarios en articulos"
    )

    Permission.objects.create(name="manejo_roles", description="Manejo de roles")

    Role.objects.get(name="Administrador").permissions.add(
        Permission.objects.get(name="ver_inicio"),
        Permission.objects.get(name="ver_categorias_suscriptor"),
        Permission.objects.get(name="ver_categorias_pago"),
        Permission.objects.get(name="crear_articulos"),
        Permission.objects.get(name="editar_articulos"),
        Permission.objects.get(name="moderar_articulos"),
        Permission.objects.get(name="publicar_comentarios"),
        Permission.objects.get(name="leer_comentarios"),
        Permission.objects.get(name="evaluar_articulos"),
        Permission.objects.get(name="manejo_roles"),
    )

    Role.objects.get(name="Suscriptor").permissions.add(
        Permission.objects.get(name="ver_inicio"),
        Permission.objects.get(name="ver_categorias_suscriptor"),
        Permission.objects.get(name="publicar_comentarios"),
        Permission.objects.get(name="leer_comentarios"),
        Permission.objects.get(name="evaluar_articulos"),
    )

    Role.objects.get(name="Editor").permissions.add(
        Permission.objects.get(name="ver_inicio"),
        Permission.objects.get(name="ver_categorias_suscriptor"),
        Permission.objects.get(name="editar_articulos"),
        Permission.objects.get(name="publicar_comentarios"),
        Permission.objects.get(name="leer_comentarios"),
        Permission.objects.get(name="evaluar_articulos"),
    )

    Role.objects.get(name="Autor").permissions.add(
        Permission.objects.get(name="ver_inicio"),
        Permission.objects.get(name="ver_categorias_suscriptor"),
        Permission.objects.get(name="crear_articulos"),
        Permission.objects.get(name="publicar_comentarios"),
        Permission.objects.get(name="leer_comentarios"),
        Permission.objects.get(name="evaluar_articulos"),
    )

    Role.objects.get(name="Publicador").permissions.add(
        Permission.objects.get(name="ver_inicio"),
        Permission.objects.get(name="ver_categorias_pago"),
        Permission.objects.get(name="publicar_comentarios"),
        Permission.objects.get(name="leer_comentarios"),
        Permission.objects.get(name="evaluar_articulos"),
        Permission.objects.get(name="moderar_articulos"),
    )

    Role.objects.get(name="Visitante").permissions.add(
        Permission.objects.get(name="ver_inicio"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0003_permission_role_permissions"),
    ]

    operations = [
        migrations.RunPython(add_default_roles),
    ]
