# Generated by Django 5.0.7 on 2024-08-30 02:04

from django.db import migrations
from roles.utils import PermissionEnum


def add_default_roles(apps, schema_editor):
    Permission = apps.get_model("roles", "permission")
    Role = apps.get_model("roles", "Role")

    Permission.objects.create(
        name=PermissionEnum.VER_INICIO,
        description="Ver solamente pantalla de inicio y categorías free",
    )

    Permission.objects.create(
        name=PermissionEnum.VER_CATEGORIAS_SUSCRIPTOR,
        description="Ver las categorías del suscriptor",
    )

    Permission.objects.create(
        name=PermissionEnum.VER_CATEGORIAS_PAGO,
        description="Ver las categorías del suscriptor",
    )

    Permission.objects.create(
        name=PermissionEnum.CREAR_ARTICULOS,
        description="Crear articulos en aquellas categorías que pueda crear",
    )

    Permission.objects.create(
        name=PermissionEnum.EDITAR_ARTICULOS,
        description="Editar articulos en aquellas categorías que pueda editar",
    )

    Permission.objects.create(
        name=PermissionEnum.MODERAR_ARTICULOS,
        description="Moderar articulos en aquellas categorías que pueda moderar",
    )

    Permission.objects.create(
        name=PermissionEnum.PUBLICAR_COMENTARIOS,
        description="Publicar comentarios en articulos",
    )

    Permission.objects.create(
        name=PermissionEnum.LEER_COMENTARIOS,
        description="Leer comentarios en articulos",
    )

    Permission.objects.create(
        name=PermissionEnum.MODERAR_ARTICULOS,
        description="Moderar comentarios en articulos",
    )

    Permission.objects.create(
        name=PermissionEnum.MANEJO_ROLES, description="Manejo de roles"
    )

    Role.objects.get(name="Administrador").permissions.add(
        Permission.objects.get(name=PermissionEnum.VER_INICIO),
        Permission.objects.get(name=PermissionEnum.VER_CATEGORIAS_SUSCRIPTOR),
        Permission.objects.get(
            name=PermissionEnum.VER_CATEGORIAS_PAGO,
        ),
        Permission.objects.get(name=PermissionEnum.CREAR_ARTICULOS),
        Permission.objects.get(
            name=PermissionEnum.EDITAR_ARTICULOS,
        ),
        Permission.objects.get(name=PermissionEnum.MODERAR_ARTICULOS),
        Permission.objects.get(name=PermissionEnum.PUBLICAR_COMENTARIOS),
        Permission.objects.get(name=PermissionEnum.LEER_COMENTARIOS),
        Permission.objects.get(name=PermissionEnum.MODERAR_ARTICULOS),
        Permission.objects.get(name=PermissionEnum.MANEJO_ROLES),
    )

    Role.objects.get(name="Suscriptor").permissions.add(
        Permission.objects.get(name=PermissionEnum.VER_INICIO),
        Permission.objects.get(name=PermissionEnum.VER_CATEGORIAS_SUSCRIPTOR),
        Permission.objects.get(name=PermissionEnum.PUBLICAR_COMENTARIOS),
        Permission.objects.get(name=PermissionEnum.LEER_COMENTARIOS),
        Permission.objects.get(name=PermissionEnum.MODERAR_ARTICULOS),
    )

    Role.objects.get(name="Editor").permissions.add(
        Permission.objects.get(name=PermissionEnum.VER_INICIO),
        Permission.objects.get(name=PermissionEnum.VER_CATEGORIAS_SUSCRIPTOR),
        Permission.objects.get(
            name=PermissionEnum.EDITAR_ARTICULOS,
        ),
        Permission.objects.get(name=PermissionEnum.PUBLICAR_COMENTARIOS),
        Permission.objects.get(name=PermissionEnum.LEER_COMENTARIOS),
        Permission.objects.get(name=PermissionEnum.MODERAR_ARTICULOS),
    )

    Role.objects.get(name="Autor").permissions.add(
        Permission.objects.get(name=PermissionEnum.VER_INICIO),
        Permission.objects.get(name=PermissionEnum.VER_CATEGORIAS_SUSCRIPTOR),
        Permission.objects.get(name=PermissionEnum.CREAR_ARTICULOS),
        Permission.objects.get(name=PermissionEnum.PUBLICAR_COMENTARIOS),
        Permission.objects.get(name=PermissionEnum.LEER_COMENTARIOS),
        Permission.objects.get(name=PermissionEnum.MODERAR_ARTICULOS),
    )

    Role.objects.get(name="Publicador").permissions.add(
        Permission.objects.get(name=PermissionEnum.VER_INICIO),
        Permission.objects.get(
            name=PermissionEnum.VER_CATEGORIAS_PAGO,
        ),
        Permission.objects.get(name=PermissionEnum.PUBLICAR_COMENTARIOS),
        Permission.objects.get(name=PermissionEnum.LEER_COMENTARIOS),
        Permission.objects.get(name="evaluar_articulos"),
        Permission.objects.get(name=PermissionEnum.MODERAR_ARTICULOS),
    )

    Role.objects.get(name="Visitante").permissions.add(
        Permission.objects.get(name=PermissionEnum.VER_INICIO),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0003_permission_role_permissions"),
    ]

    operations = [
        migrations.RunPython(add_default_roles),
    ]
