# Generated by Django 5.0.7 on 2024-11-04 23:28

from django.db import migrations
from roles.utils import PermissionEnum

def add_default_roles(apps, schema_editor):
    Permission = apps.get_model("roles", "Permission")
    Role = apps.get_model("roles", "Role")

    role_administrador = Role.objects.get(name="Administrador")

    role_administrador.permissions.add(
        Permission.objects.get(name=PermissionEnum.VER_CATEGORIAS),
    )

class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_agregar_listar_categorias'),
    ]

    operations = [
        migrations.RunPython(add_default_roles)
    ]
