# Generated by Django 5.0.7 on 2024-11-05 22:56

from django.db import migrations
from roles.utils import PermissionEnum


def add_default_roles(apps, schema_editor):
    Permission = apps.get_model("roles", "Permission")
    Role = apps.get_model("roles", "Role")

    permiso_kanban = Permission.objects.create(
        name=PermissionEnum.VER_KANBAN,
        description="Permite acceder a la vista del kanban",
    )

    Role.objects.get(name="Administrador").permissions.add(permiso_kanban)
    Role.objects.get(name="Editor").permissions.add(permiso_kanban)
    Role.objects.get(name="Autor").permissions.add(permiso_kanban)
    Role.objects.get(name="Publicador").permissions.add(permiso_kanban)

class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0009_agregar_listar_categorias_admin"),
    ]

    operations = [migrations.RunPython(add_default_roles)]
