# Generated by Django 5.0.7 on 2024-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0004_add_primeros_permisos"),
        ("user", "0002_remove_customuser_roles_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.AddField(
            model_name="customuser",
            name="roles",
            field=models.ManyToManyField(to="roles.role"),
        ),
    ]
